apiVersion: skaffold/v2beta2
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s/*
build:
  local:
    push: false
  artifacts:
    - image: tkircsi/complex-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.html'
            dest: .
    - image: tkircsi/complex-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.html'
            dest: .